### ISSUE TITLE
images for intro

### ISSUE THREAD

**Issue by oleggantmedia** [Teplitsa/kandinsky-text#7]
![4](https://user-images.githubusercontent.com/9340363/29362975-bf008d60-8296-11e7-925a-796dde31c586.jpg)
![6](https://user-images.githubusercontent.com/9340363/29362977-bf01478c-8296-11e7-87d9-a3dc60080e13.jpg)
![7](https://user-images.githubusercontent.com/9340363/29362974-bf002262-8296-11e7-8ec4-0f3314e9cecd.jpg)
![8](https://user-images.githubusercontent.com/9340363/29362979-bf042402-8296-11e7-80e1-bca616b4cf59.jpg)
![10](https://user-images.githubusercontent.com/9340363/29362976-bf00d1f8-8296-11e7-90aa-2988786a9130.jpg)
![13](https://user-images.githubusercontent.com/9340363/29362978-bf01b208-8296-11e7-876c-5baada993779.jpg)

**Comment by sidorenkoa** [comment]
Олег, а ты решил цветовые фильтры не применять? Или мы не так поняли друг друга?
![2017-kandinsky-filters](https://user-images.githubusercontent.com/1734146/29364451-bbaff66c-8293-11e7-9f16-3471b723ffea.jpg)

**Comment by oleggantmedia** [comment]
Я применил тонировку по цветам. Я не думал, что мы будем сплошную заливку делать.

**Comment by foralien** [comment]
я затрудняюсь сказать что лучше, потому что надо посмотреть как это будет на живом работать - займусь этим. 
То что предлагает Олег - конечно более такая точная работа с изображением и как следствие более трудоемкая, хотя эффект конечно крутой от нее. 
Касательно заливки - может быть мы в каких-то случаях будем использовать этот прием тоже, но наверное не на всех изображениях.

**Comment by foralien** [comment]
![2017-08-16 16 53 09](https://user-images.githubusercontent.com/3698643/29366727-7e95c792-82a3-11e7-9f95-3760e524b7a3.png)
не удержалась от того, чтобы попробовать дядю на заставке )

**Comment by oleggantmedia** [comment]
Давайте попробуем и то и другое, но обычно полный color grading делается на кино постерах, иногда в рекламе, в событийных фотографиях, скажем в офисе, это будет создавать картину не реалистичности, мне кажется, и какой-то цветовой стены между пользователем.

**Comment by sidorenkoa** [comment]
![2017-gamma](https://user-images.githubusercontent.com/1734146/29368536-59310366-82a0-11e7-86e9-8085f1dcb001.jpg)

**Comment by oleggantmedia** [comment]
Может через градиент с менее плотной заливкой?
![2017-08-17 13 38 39](https://user-images.githubusercontent.com/9340363/29408605-8310d2cc-8351-11e7-8b3e-d9e99678aa93.png)

**Comment by oleggantmedia** [comment]
Два цвета синий в тенях, желтый в светах.

**Comment by oleggantmedia** [comment]
Давайте решим, чтобы я смог переделать и перезалить.

**Comment by oleggantmedia** [comment]
![2017-08-17 13 47 23](https://user-images.githubusercontent.com/9340363/29409014-18629a9e-8353-11e7-97b5-067d72f619d3.png)
![2017-08-17 13 50 18](https://user-images.githubusercontent.com/9340363/29409015-186491a0-8353-11e7-9e2f-1758f0a68e7f.png)

**Comment by sidorenkoa** [comment]
Олег, перезалей пока те, что есть, Аня дальше решит, будет она заполнять цветом или нет. Тем более фильтры, которые ты предлагаешь, они все равно по-другому работают и не дают соответствия выбранному цвету. 

Ты используешь фильтры, а нужно наложение цвета. С фильтрами нельзя сказать "хочу, чтобы гармонировало с #ffc400". Поэтому просто выложи, а там уже Аня доделает.
